In [137]:
# series的创建
import pandas as pd
s = pd.Series([10,2,3,4,5])
print(s)
# 自定义索引
s = pd.Series([10,2,3,4,5],index=['A','B','C','D','E'])
#s = pd.Series([10,2,3,4,5],index=[1,2,3,4,5])
print(s)

#定义name
s = pd.Series([10,2,3,4,5],index=['A','B','C','D','E'],name='月份')
print(s)

0    10
1     2
2     3
3     4
4     5
dtype: int64
A    10
B     2
C     3
D     4
E     5
dtype: int64
A    10
B     2
C     3
D     4
E     5
Name: 月份, dtype: int64

In [145]:
# 通过字典来创建对象
s = pd.Series({"a":1,"b":2,"c":3,"d":4,"e":5})
print(s)
s2 = pd.Series([10,2,3,4,5],index=['A','B','C','D','E'],name='月份')
s1 = pd.Series(s2,index=["A","C"])
s3 = pd.Series(s,index=["a","c"])
print(s1)
print(s3)

a    1
b    2
c    3
d    4
e    5
dtype: int64
A    10
C     3
Name: 月份, dtype: int64
a    1
c    3
dtype: int64

In [167]:
# series的属性
# index:Series的索引对象
# values:Series的值
# dtype或dtypes:Series的元素类型
# shape:Series的形状
# ndim:Series的维度
# size:Series的元素个数
# name:Series的名称
# loc[]显式索引，按标签索引或切片
# iloc[]隐式索引，按位置索引或切片
# at[]使用标签访问单个元素
# iat[]使用位置访问单个元素
s.name = 'test'
print(s.index)
print(s.values)
print(s.shape,s.ndim,s.size)
print(s.dtype,s.name)
print(s.loc['a':'c'])#显式索引 支持切片 按标签
print(s.iloc[0:5]) #隐式索引 支持切片 按位置
print(s.at['a'])#不支持切片 找精确值 显式 按标签
print(s.iat[0])#不支持切片 找精确值 隐式 按位置

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]
(5,) 1 5
int64 test
a    1
b    2
c    3
Name: test, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: test, dtype: int64
1
1

In [176]:
# 访问数据
#print(s[0])#直接访问,存在waring，不知道为标签和位置，默认为位置
print(s['a'])#标签访问
print(s)
print(s[s<3])#布尔索引
s['f'] = 6
print(s.head(2))#s.head默认打印前五行，查看前n行数据
print(s.tail(1))#s.tail默认打印后五行，查看后n行数据

1
a    1
b    2
c    3
d    4
e    5
f    6
Name: test, dtype: int64
a    1
b    2
Name: test, dtype: int64
a    1
b    2
Name: test, dtype: int64
f    6
Name: test, dtype: int64

In [190]:
#常见函数
s = pd.Series([10,2,np.nan,None,3,4,5],index=['A','B','C','D','E','F','G'],name='data')
print(s)

A    10.0
B     2.0
C     NaN
D     NaN
E     3.0
F     4.0
G     5.0
Name: data, dtype: float64

In [195]:
s.head(3)#默认取前五行数据
s.tail(6)#默认取后五行数据

B    2.0
C    NaN
D    NaN
E    3.0
F    4.0
G    5.0
Name: data, dtype: float64

In [197]:
#查看所有的描述性信息
s.describe()

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64

In [202]:
#获取元素个数 (忽略缺失值)
print(s.count())

5

In [208]:
#获取索引
print(s.keys()) #通过方法获取索引
print(s.index) #通过属性获取索引

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')

In [212]:
print(s.isna()) #检查Series里的每一个元素是否为缺失值
s.isna()

A    False
B    False
C     True
D     True
E    False
F    False
G    False
Name: data, dtype: bool

A    False
B    False
C     True
D     True
E    False
F    False
G    False
Name: data, dtype: bool

In [216]:
s.isin([4,5,6]) # 检查每个元素是否在参数集合中

A    False
B    False
C    False
D    False
E    False
F     True
G     True
Name: data, dtype: bool

In [218]:
s.describe()

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64

In [222]:
print(s.mean())#平均值
print(s.sum())#总和
print(s.std())#标准差
print(s.var())#方差
print(s.min())#最小值
print(s.max())#最大值
print(s.median())#中位数

4.8
24.0
3.1144823004794877
9.700000000000001
2.0
10.0
4.0

In [228]:
print(s.sort_values())#排序
print(s.quantile(0.8))#分位数
#______________
#2  3  4  5  10
#共4段，4*0.8=3.2 3.2-3=0.2 5+5*0.2=6

B     2.0
E     3.0
F     4.0
G     5.0
A    10.0
C     NaN
D     NaN
Name: data, dtype: float64
6.000000000000001

In [231]:
#众数
s['H'] = 4
print(s.mode())

0    4.0
Name: data, dtype: float64

In [233]:
print(s.value_counts()) #每个元素的计数

data
4.0     2
10.0    1
2.0     1
3.0     1
5.0     1
Name: count, dtype: int64

In [238]:
s.drop_duplicates()#去重方法 返回为Series
s.unique()# 也为去重 返回为list 
print(s.nunique())#去除重复后保留元素的个数

5

In [241]:
#排序 值、索引
s.sort_index()  #按索引排序
s.sort_values() #按值排序

B     2.0
E     3.0
F     4.0
H     4.0
G     5.0
A    10.0
C     NaN
D     NaN
Name: data, dtype: float64

# pandas_series案例

In [254]:
import numpy as np
import pandas as pd
np.random.seed(42)
#scores = pd.Series(np.random.randint(50,101,10),index = ['学生' + str(i) for i in range(1,11)])
values = np.random.randint(50,101,10)
index = []
for i in range(1,11):
    index.append('学生'+str(i))
scores = pd.Series(values,index)
print(scores)
average = scores.mean()
max = scores.max()
min = scores.min()
print("平均分为：",average)
print("最高分为：",max)
print("最低分为：",min)
over_average = scores[scores>average]
print(len(over_average))
print(over_average)
print('超越个数为',over_average.count())

学生1     88
学生2     78
学生3     64
学生4     92
学生5     57
学生6     70
学生7     88
学生8     68
学生9     72
学生10    60
dtype: int32
平均分为： 73.7
最高分为： 92
最低分为： 57
4
学生1    88
学生2    78
学生4    92
学生7    88
dtype: int32
超越个数为 4

In [278]:
import pandas as pd
temperatures = pd.Series([28,31,29,32,30,27,33],index=['周一','周二','周三','周四','周五','周六','周日'])
over_temperature_30 = temperatures[temperatures>30]
print("超过30度的天数：",over_temperature_30.count())
mean = temperatures.mean()
print("平均温度为：",mean)
t2 = temperatures.sort_values(ascending =False)
print("从高到低排序为：\n",t2)
#找出温度变化最大的两天
#28 31 29 32 30 27 33
#none 3 -2 3 -2 -3 6
t3 = temperatures.diff().abs()#后一元素和前一个元素的差值 计算series的变化值
print("温度变化最大的两天",*(t3.sort_values(ascending=False).keys()[:2].tolist()))#*()去掉中括号 ， tolist把index对象变为列表
#t3.sort_values(ascending=False).index

超过30度的天数： 3
平均温度为： 30.0
从高到低排序为：
 周日    33
周四    32
周二    31
周五    30
周三    29
周一    28
周六    27
dtype: int64
温度变化最大的两天 周日 周二

In [9]:
import pandas as pd
import numpy as np

#日期序列
#date = pd.date_range('2026-09-27',periods=6)
#print(list(date))
prices = pd.Series([102.3,103.5,105.1,104.8,106.2,107.0,106.5,108.1,109.3,110.2], index=pd.date_range('2023-01-01',periods=10))
#print(prices)

In [17]:
#计算每日收益率
profit = prices.pct_change() #percent_change 2023-01-02 103.5/102.3 - 1 算每日收益率

In [15]:
#收益率最高的日期
print(profit.idxmax())
#收益率最低的日期
print(profit.idxmin())

2023-01-03 00:00:00
2023-01-07 00:00:00

In [18]:
#波动率
print(profit.std())

0.007373623845361105

In [6]:
import pandas as pd
import numpy as np
sales = pd.Series([120,135,145,160,155,170,180,175,190,200,210,220],index=pd.date_range('2022-01-01',periods=12,freq='MS'))
print(sales)

2022-01-01    120
2022-02-01    135
2022-03-01    145
2022-04-01    160
2022-05-01    155
2022-06-01    170
2022-07-01    180
2022-08-01    175
2022-09-01    190
2022-10-01    200
2022-11-01    210
2022-12-01    220
Freq: MS, dtype: int64

In [11]:
#季度的平均销量 sales
sales.resample('QS').count()
#sales.resample('YS').mean() == sales.mean() 因为样本就是12个月
sales.resample('QS').mean()#resample()重新采样 'QS'每个季度的开始
sales.resample('QS').sum()

2022-01-01    400
2022-04-01    485
2022-07-01    545
2022-10-01    630
Freq: QS-JAN, dtype: int64

In [13]:
print('销量最高的月份',sales.idxmax())

销量最高的月份 2022-12-01 00:00:00

In [22]:
print('月环比的增长率：',pct_change)
pct_change = sales.pct_change()
pct_change_judge = pct_change>0
#用滑动窗口来看是否存在连续两个月增长
pct_change_judge[pct_change_judge.rolling(3).sum() == 3].keys().tolist()

月环比的增长率： 2022-01-01         NaN
2022-02-01    0.125000
2022-03-01    0.074074
2022-04-01    0.103448
2022-05-01   -0.031250
2022-06-01    0.096774
2022-07-01    0.058824
2022-08-01   -0.027778
2022-09-01    0.085714
2022-10-01    0.052632
2022-11-01    0.050000
2022-12-01    0.047619
Freq: MS, dtype: float64

[Timestamp('2022-04-01 00:00:00'),
 Timestamp('2022-11-01 00:00:00'),
 Timestamp('2022-12-01 00:00:00')]

In [55]:
import pandas as pd
import numpy as np
np.random.seed(42)
hourly_sales = pd.Series(np.random.randint(0,100,24),
                        index=pd.date_range('2025-01-01',periods=24,freq='h'))
print(hourly_sales)
#按天进行重采样计算每日总销售额
day_sales = hourly_sales.resample('D').sum()
#计算每天营业时间（8：00-22：00）和非营业时间销售额的比例
#hourly_sales.between_time('8:00', '22:00')#筛选一段时间内的series ，between_time方式计算一段时间销售额
business_hours_sales = hourly_sales[(hourly_sales.index.hour>=8) & (hourly_sales.index.hour <= 22)]#布尔索引方式计算一段时间销售额
#print(business_hours_sales.sum()/(day_sales - business_hours_sales.sum()))
not_business_hours_sales = hourly_sales.drop(business_hours_sales.index)#drop()去除原有系列中的一部分系列
print(business_hours_sales.sum()/not_business_hours_sales.sum())
#此外取反也行

#找出销售额最高的三个小时
print(hourly_sales.nlargest(3).index.tolist())

2025-01-01 00:00:00    51
2025-01-01 01:00:00    92
2025-01-01 02:00:00    14
2025-01-01 03:00:00    71
2025-01-01 04:00:00    60
2025-01-01 05:00:00    20
2025-01-01 06:00:00    82
2025-01-01 07:00:00    86
2025-01-01 08:00:00    74
2025-01-01 09:00:00    74
2025-01-01 10:00:00    87
2025-01-01 11:00:00    99
2025-01-01 12:00:00    23
2025-01-01 13:00:00     2
2025-01-01 14:00:00    21
2025-01-01 15:00:00    52
2025-01-01 16:00:00     1
2025-01-01 17:00:00    87
2025-01-01 18:00:00    29
2025-01-01 19:00:00    37
2025-01-01 20:00:00     1
2025-01-01 21:00:00    63
2025-01-01 22:00:00    59
2025-01-01 23:00:00    20
Freq: h, dtype: int32
1.4294354838709677
[Timestamp('2025-01-01 11:00:00'), Timestamp('2025-01-01 01:00:00'), Timestamp('2025-01-01 10:00:00')]

# 3.Pandas_DataFrame

In [70]:
#dataframe的创建方式
import pandas as pd
import numpy as np
#通过series来创建
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({"第一列":s1,"第二列":s2})
#通过字典来创建
df = pd.DataFrame(
    {
        "id":[1,2,3,4,5],
        "name":["tom","jack","alice","bob","alien"],
        "age":[15,17,20,26,30],
        "score":[60.5,80,30.6,70,83.5]
    },
    index=[1,2,3,4,5],columns=["name","score","age","id"]
)
df

    name  score  age  id
1    tom   60.5   15   1
2   jack   80.0   17   2
3  alice   30.6   20   3
4    bob   70.0   26   4
5  alien   83.5   30   5

In [76]:
# dataframe的属性
print('行索引：',df.index)
print('列标签：',df.columns)
print('值')
print(df.values)

行索引： Index([1, 2, 3, 4, 5], dtype='int64')
列标签： Index(['name', 'score', 'age', 'id'], dtype='object')
值
[['tom' 60.5 15 1]
 ['jack' 80.0 17 2]
 ['alice' 30.6 20 3]
 ['bob' 70.0 26 4]
 ['alien' 83.5 30 5]]

In [83]:
print('维度：',df.ndim)
print('形状：',df.shape)
print('元素个数：',df.size)
print('数据类型：')
print(df.dtypes)

维度： 2
形状： (5, 4)
元素个数： 20
数据类型：
name      object
score    float64
age        int64
id         int64
dtype: object

In [89]:
#行列转置
print(df.T)
print(df.T.index)
print(df.T.columns)

          1     2      3     4      5
name    tom  jack  alice   bob  alien
score  60.5  80.0   30.6  70.0   83.5
age      15    17     20    26     30
id        1     2      3     4      5
Index(['name', 'score', 'age', 'id'], dtype='object')
Index([1, 2, 3, 4, 5], dtype='int64')

In [95]:
#获取元素 loc iloc at iat
#获取某行元素
print(df.loc[4]) #index显式为4
print(df.iloc[3]) #隐式为位置3
#获取某列数据
print(df.loc[:,'name'])#显式
print(df.iloc[:,0])#隐式

name      bob
score    70.0
age        26
id          4
Name: 4, dtype: object
name      bob
score    70.0
age        26
id          4
Name: 4, dtype: object
1      tom
2     jack
3    alice
4      bob
5    alien
Name: name, dtype: object
1      tom
2     jack
3    alice
4      bob
5    alien
Name: name, dtype: object

In [101]:
#获取单个数据
print(df.at[3,'score'])
print(df.iat[2,1])
print(df.loc[3,'score'])
print(df.iloc[2,1])

30.6
30.6
30.6
30.6

In [109]:
# 获取单列数据
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))
print(df[['name']])
print(type(df[['name']]))
df[['name']]

1      tom
2     jack
3    alice
4      bob
5    alien
Name: name, dtype: object
<class 'pandas.core.series.Series'>
1      tom
2     jack
3    alice
4      bob
5    alien
Name: name, dtype: object
<class 'pandas.core.series.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  alien
<class 'pandas.core.frame.DataFrame'>

    name
1    tom
2   jack
3  alice
4    bob
5  alien

In [112]:
print(df[['name','score']])# 多列数据的获取，属性为DataFrame

    name  score
1    tom   60.5
2   jack   80.0
3  alice   30.6
4    bob   70.0
5  alien   83.5

In [116]:
#查看部分数据
print(df.head(2))
print(df.tail(3))

   name  score  age  id
1   tom   60.5   15   1
2  jack   80.0   17   2
    name  score  age  id
3  alice   30.6   20   3
4    bob   70.0   26   4
5  alien   83.5   30   5

In [121]:
#使用布尔索引筛选数据
df[df.score>70]
df[(df.score>70) & (df.age<20)]

   name  score  age  id
2  jack   80.0   17   2

In [123]:
# 随机抽样
df.sample(3)

    name  score  age  id
2   jack   80.0   17   2
3  alice   30.6   20   3
1    tom   60.5   15   1

In [15]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "name":["tom","jack","alice","bob","allen"],
        "age":[15,15,20,26,30],
        "score":[60.5,80,30.6,70,83.5]        
    },
    index = [1,2,3,4,5],
    columns=["name","score","age"]
)

In [3]:
print(df.head())
print(df.tail(1))

    name  score  age
1    tom   60.5   15
2   jack   80.0   17
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30
    name  score  age
5  allen   83.5   30

In [7]:
print(df.isin(['jack',20])) #查看元素是否包含在参数集合中

    name  score    age
1  False  False  False
2   True  False  False
3  False  False   True
4  False  False  False
5  False  False  False

In [9]:
print(df.isna())#查看元素是否为缺失值

    name  score    age
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [18]:
print(df['score'].sum()) #某一列的总和
print(df.score.max()) #最大值
print(df.age.min()) #最小值
print(df.score.mean()) #平均值
print(df.score.median()) #中位数
print(df.age.mode()) #众数

324.6
83.5
15
64.92
70.0
0    15
Name: age, dtype: int64

In [22]:
print(df.score.std()) #标准差
print(df.score.var()) #方差
print(df.score.quantile(0.25)) #分位数

21.188605428390044
448.957
60.5

In [24]:
print(df.describe())

           score        age
count   5.000000   5.000000
mean   64.920000  21.200000
std    21.188605   6.685806
min    30.600000  15.000000
25%    60.500000  15.000000
50%    70.000000  20.000000
75%    80.000000  26.000000
max    83.500000  30.000000

In [26]:
print(df.count()) # 返回每一列非缺失值个数

name     5
score    5
age      5
dtype: int64

In [28]:
print(df.value_counts()) #出现的次数

name   score  age
alice  30.6   20     1
allen  83.5   30     1
bob    70.0   26     1
jack   80.0   15     1
tom    60.5   15     1
Name: count, dtype: int64

In [29]:
print(df.drop_duplicates()) #去重

    name  score  age
1    tom   60.5   15
2   jack   80.0   15
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [34]:
print(df.duplicated(subset=['age']))#检查是否有重复，可以选定列进行检查

1    False
2     True
3    False
4    False
5    False
dtype: bool

In [36]:
df.sample(2)#随机抽样

    name  score  age
4    bob   70.0   26
5  allen   83.5   30

In [39]:
print(df.replace(15,30))#替换，将所有15替换为30

    name  score  age
1    tom   60.5   30
2   jack   80.0   30
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [41]:
df

    name  score  age
1    tom   60.5   15
2   jack   80.0   15
3  alice   30.6   20
4    bob   70.0   26
5  allen   83.5   30

In [45]:
df.cumsum() # 累计和
df.cummax() #累积最大
df.cummin() #累积最小，默认为按列累积，如果要换成行累积需要使用axis轴表示 ,axis=0为按列，axis=1为按行

    name  score  age
1    tom   60.5   15
2   jack   60.5   15
3  alice   30.6   15
4  alice   30.6   15
5  alice   30.6   15

In [48]:
df.cummin(axis = 1)#这里报错是因为一行中存在字符

TypeError: '<=' not supported between instances of 'str' and 'float'

In [50]:
print(df.sort_index(ascending=False))

    name  score  age
5  allen   83.5   30
4    bob   70.0   26
3  alice   30.6   20
2   jack   80.0   15
1    tom   60.5   15

In [56]:
print(df.sort_values(by='name'))

    name  score  age
3  alice   30.6   20
5  allen   80.0   30
4    bob   70.0   26
2   jack   80.0   15
1    tom   60.5   15

In [55]:
df = pd.DataFrame(
    {
        "name":["tom","jack","alice","bob","allen"],
        "age":[15,15,20,26,30],
        "score":[60.5,80,30.6,70,80]        
    },
    index = [1,2,3,4,5],
    columns=["name","score","age"]
)

In [60]:
print(df.sort_values(by=['score','age'],ascending=[True,False]))

    name  score  age
3  alice   30.6   20
1    tom   60.5   15
4    bob   70.0   26
5  allen   80.0   30
2   jack   80.0   15

In [63]:
df.nlargest(2,columns=['score','age'])
df.nsmallest(2,columns=['score','age'])

    name  score  age
3  alice   30.6   20
1    tom   60.5   15

In [112]:
import pandas as pd
data = {
    '姓名':['张三','李四','王五','赵六','钱七'],
    '数学':[85,92,78,88,95],
    '英语':[90,88,85,92,80],
    '物理':[75,80,88,85,90]
}

scores = pd.DataFrame(data,index=[1,2,3,4,5],columns=['姓名','数学','英语','物理'])
#计算每位学生的总分和平均分
scores['总分'] = scores[['数学','英语','物理']].sum(axis=True)
#print('张三总和为：',scores.loc[1,'数学':'物理'].sum())
#scores['平均分'] = scores[['数学','英语','物理']].mean(axis=True)
scores['平均分'] = scores['总分'] / 3
#找出数学平均分高于90分或英语成绩高于85分的学生
print(scores[(scores['数学']>90) | (scores['英语']>85)])
#按总分从高到低排序，并输出前三名学生
r1 = scores.sort_values('总分',ascending=False).head(3)
r2 = scores.nlargest(3,columns=['总分'])
print(r1)
print(r2)

   姓名  数学  英语  物理   总分        平均分
1  张三  85  90  75  250  83.333333
2  李四  92  88  80  260  86.666667
4  赵六  88  92  85  265  88.333333
5  钱七  95  80  90  265  88.333333
   姓名  数学  英语  物理   总分        平均分
4  赵六  88  92  85  265  88.333333
5  钱七  95  80  90  265  88.333333
2  李四  92  88  80  260  86.666667
   姓名  数学  英语  物理   总分        平均分
4  赵六  88  92  85  265  88.333333
5  钱七  95  80  90  265  88.333333
2  李四  92  88  80  260  86.666667

In [127]:
import pandas as pd

data = {
    '产品名称':['A','B','C','D'],
    '单价':[100,150,200,120],
    '销量':[50,30,20,40]
}

products = pd.DataFrame(data,index=[1,2,3,4],columns=['产品名称','单价','销量'])
products['总销售额'] = products['单价']*products['销量']
print(products.nlargest(1,columns=['总销售额']))
products.sort_values('总销售额',ascending = False)

  产品名称   单价  销量  总销售额
1    A  100  50  5000

  产品名称   单价  销量  总销售额
1    A  100  50  5000
4    D  120  40  4800
2    B  150  30  4500
3    C  200  20  4000

In [1]:
import pandas as pd

data = {
    '用户ID':[101,102,103,104,105],
    '用户名':['Alice','Bob','Charlie','David','Eve'],
    '商品类别':['电子产品','服饰','电子产品','家居','服饰'],
    '商品单价':[1200,300,800,150,200],
    '购买数量':[1,3,2,5,4]
}

products = pd.DataFrame(data,index=[1,2,3,4,5],columns=['用户ID','用户名','商品类别','商品单价','购买数量'])
#计算每位用户的总消费金额
products['总消费金额'] = products['商品单价']*products['购买数量']
#找出消费金额最高的用户，并输出其所有信息
products.nlargest(1,columns = ['总消费金额'])
#计算所有用户的平均消费金额
products['总消费金额'].mean()
#计算电子产品的总购买数量
products[products['商品类别'] == '电子产品']['购买数量'].sum()

np.int64(3)

In [20]:
#数据的导入
import pandas as pd
df = pd.read_csv('untitled.csv')
print(type(df))
print(df.tail())
print(df['单价'].mean())

#数据的导出
df.to_csv('new_commodity.csv')

<class 'pandas.core.frame.DataFrame'>
             日期   商品   类别   销量    单价     销售额
795  2026-09-16   酸奶  乳制品   25   9.5   237.5
796  2026-09-17   牛奶  乳制品  234  12.0  2808.0
797  2026-09-18   香蕉   水果   74   3.2   236.8
798  2026-09-19   橙子   水果  130   6.0   780.0
799  2026-09-20  鸡胸肉   肉禽  195  22.0  4290.0
21.6355

In [45]:
#json数据的导入
df = pd.read_json('new_json.json')
print(type(df))

import json
with open('sales_data.json',encoding = 'UTF-8') as f:
    data = json.load(f)
print(data['records']) 
print(type(data))
df = pd.DataFrame(data['records'])
df1 = pd.DataFrame(df['product'])
df1

<class 'pandas.core.frame.DataFrame'>
[{'order_id': 'SO20260900', 'date': '2026-09-01', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '酸奶', 'category': '乳制品', 'unit_price': 9.5}, 'quantity': 106, 'total_amount': 1007.0, 'payment_method': '微信'}, {'order_id': 'SO20260901', 'date': '2026-09-02', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '香蕉', 'category': '水果', 'unit_price': 3.2}, 'quantity': 29, 'total_amount': 92.8, 'payment_method': '银行卡'}, {'order_id': 'SO20260902', 'date': '2026-09-03', 'store': '广州天河店', 'region': '华南', 'product': {'name': '三文鱼', 'category': '水产', 'unit_price': 45.0}, 'quantity': 134, 'total_amount': 6030.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260903', 'date': '2026-09-04', 'store': '广州天河店', 'region': '华南', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 116, 'total_amount': 986.0, 'payment_method': '现金'}, {'order_id': 'SO20260904', 'date': '2026-09-05', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '香蕉', 'category': '水果', 'unit_price': 3.2}, 'quantity': 28, 'total_amount': 89.6, 'payment_method': '现金'}, {'order_id': 'SO20260905', 'date': '2026-09-06', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 36, 'total_amount': 306.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260906', 'date': '2026-09-07', 'store': '广州天河店', 'region': '华南', 'product': {'name': '三文鱼', 'category': '水产', 'unit_price': 45.0}, 'quantity': 152, 'total_amount': 6840.0, 'payment_method': '现金'}, {'order_id': 'SO20260907', 'date': '2026-09-08', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 16, 'total_amount': 136.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260908', 'date': '2026-09-09', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '牛奶', 'category': '乳制品', 'unit_price': 12.0}, 'quantity': 41, 'total_amount': 492.0, 'payment_method': '微信'}, {'order_id': 'SO20260909', 'date': '2026-09-10', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '三文鱼', 'category': '水产', 'unit_price': 45.0}, 'quantity': 148, 'total_amount': 6660.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260910', 'date': '2026-09-11', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '香蕉', 'category': '水果', 'unit_price': 3.2}, 'quantity': 151, 'total_amount': 483.2, 'payment_method': '支付宝'}, {'order_id': 'SO20260911', 'date': '2026-09-12', 'store': '广州天河店', 'region': '华南', 'product': {'name': '酸奶', 'category': '乳制品', 'unit_price': 9.5}, 'quantity': 145, 'total_amount': 1377.5, 'payment_method': '微信'}, {'order_id': 'SO20260912', 'date': '2026-09-13', 'store': '广州天河店', 'region': '华南', 'product': {'name': '三文鱼', 'category': '水产', 'unit_price': 45.0}, 'quantity': 163, 'total_amount': 7335.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260913', 'date': '2026-09-14', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '蛋糕', 'category': '烘焙', 'unit_price': 28.0}, 'quantity': 114, 'total_amount': 3192.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260914', 'date': '2026-09-15', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '蛋糕', 'category': '烘焙', 'unit_price': 28.0}, 'quantity': 121, 'total_amount': 3388.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260915', 'date': '2026-09-16', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '牛奶', 'category': '乳制品', 'unit_price': 12.0}, 'quantity': 51, 'total_amount': 612.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260916', 'date': '2026-09-17', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '香蕉', 'category': '水果', 'unit_price': 3.2}, 'quantity': 81, 'total_amount': 259.2, 'payment_method': '现金'}, {'order_id': 'SO20260917', 'date': '2026-09-18', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '酸奶', 'category': '乳制品', 'unit_price': 9.5}, 'quantity': 78, 'total_amount': 741.0, 'payment_method': '微信'}, {'order_id': 'SO20260918', 'date': '2026-09-19', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '香蕉', 'category': '水果', 'unit_price': 3.2}, 'quantity': 112, 'total_amount': 358.4, 'payment_method': '支付宝'}, {'order_id': 'SO20260919', 'date': '2026-09-20', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '酸奶', 'category': '乳制品', 'unit_price': 9.5}, 'quantity': 130, 'total_amount': 1235.0, 'payment_method': '现金'}, {'order_id': 'SO20260920', 'date': '2026-09-21', 'store': '广州天河店', 'region': '华南', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 200, 'total_amount': 1700.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260921', 'date': '2026-09-22', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '酸奶', 'category': '乳制品', 'unit_price': 9.5}, 'quantity': 157, 'total_amount': 1491.5, 'payment_method': '现金'}, {'order_id': 'SO20260922', 'date': '2026-09-23', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '三文鱼', 'category': '水产', 'unit_price': 45.0}, 'quantity': 22, 'total_amount': 990.0, 'payment_method': '微信'}, {'order_id': 'SO20260923', 'date': '2026-09-24', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '牛奶', 'category': '乳制品', 'unit_price': 12.0}, 'quantity': 183, 'total_amount': 2196.0, 'payment_method': '微信'}, {'order_id': 'SO20260924', 'date': '2026-09-25', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 170, 'total_amount': 1445.0, 'payment_method': '现金'}, {'order_id': 'SO20260925', 'date': '2026-09-26', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '牛奶', 'category': '乳制品', 'unit_price': 12.0}, 'quantity': 176, 'total_amount': 2112.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260926', 'date': '2026-09-27', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 95, 'total_amount': 807.5, 'payment_method': '支付宝'}, {'order_id': 'SO20260927', 'date': '2026-09-28', 'store': '广州天河店', 'region': '华南', 'product': {'name': '三文鱼', 'category': '水产', 'unit_price': 45.0}, 'quantity': 131, 'total_amount': 5895.0, 'payment_method': '微信'}, {'order_id': 'SO20260928', 'date': '2026-09-29', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '葡萄', 'category': '水果', 'unit_price': 12.8}, 'quantity': 38, 'total_amount': 486.4, 'payment_method': '支付宝'}, {'order_id': 'SO20260929', 'date': '2026-09-30', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '面包', 'category': '烘焙', 'unit_price': 15.0}, 'quantity': 132, 'total_amount': 1980.0, 'payment_method': '微信'}, {'order_id': 'SO20260930', 'date': '2026-09-01', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '橙子', 'category': '水果', 'unit_price': 6.0}, 'quantity': 107, 'total_amount': 642.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260931', 'date': '2026-09-02', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '橙子', 'category': '水果', 'unit_price': 6.0}, 'quantity': 145, 'total_amount': 870.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260932', 'date': '2026-09-03', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '面包', 'category': '烘焙', 'unit_price': 15.0}, 'quantity': 179, 'total_amount': 2685.0, 'payment_method': '现金'}, {'order_id': 'SO20260933', 'date': '2026-09-04', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '葡萄', 'category': '水果', 'unit_price': 12.8}, 'quantity': 26, 'total_amount': 332.8, 'payment_method': '支付宝'}, {'order_id': 'SO20260934', 'date': '2026-09-05', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '橙子', 'category': '水果', 'unit_price': 6.0}, 'quantity': 173, 'total_amount': 1038.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260935', 'date': '2026-09-06', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 155, 'total_amount': 1317.5, 'payment_method': '支付宝'}, {'order_id': 'SO20260936', 'date': '2026-09-07', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '牛奶', 'category': '乳制品', 'unit_price': 12.0}, 'quantity': 6, 'total_amount': 72.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260937', 'date': '2026-09-08', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '面包', 'category': '烘焙', 'unit_price': 15.0}, 'quantity': 99, 'total_amount': 1485.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260938', 'date': '2026-09-09', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '橙子', 'category': '水果', 'unit_price': 6.0}, 'quantity': 163, 'total_amount': 978.0, 'payment_method': '微信'}, {'order_id': 'SO20260939', 'date': '2026-09-10', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '蛋糕', 'category': '烘焙', 'unit_price': 28.0}, 'quantity': 105, 'total_amount': 2940.0, 'payment_method': '现金'}, {'order_id': 'SO20260940', 'date': '2026-09-11', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '面包', 'category': '烘焙', 'unit_price': 15.0}, 'quantity': 31, 'total_amount': 465.0, 'payment_method': '现金'}, {'order_id': 'SO20260941', 'date': '2026-09-12', 'store': '广州天河店', 'region': '华南', 'product': {'name': '面包', 'category': '烘焙', 'unit_price': 15.0}, 'quantity': 53, 'total_amount': 795.0, 'payment_method': '微信'}, {'order_id': 'SO20260942', 'date': '2026-09-13', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '葡萄', 'category': '水果', 'unit_price': 12.8}, 'quantity': 46, 'total_amount': 588.8, 'payment_method': '微信'}, {'order_id': 'SO20260943', 'date': '2026-09-14', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '酸奶', 'category': '乳制品', 'unit_price': 9.5}, 'quantity': 18, 'total_amount': 171.0, 'payment_method': '微信'}, {'order_id': 'SO20260944', 'date': '2026-09-15', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 43, 'total_amount': 365.5, 'payment_method': '微信'}, {'order_id': 'SO20260945', 'date': '2026-09-16', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '酸奶', 'category': '乳制品', 'unit_price': 9.5}, 'quantity': 11, 'total_amount': 104.5, 'payment_method': '微信'}, {'order_id': 'SO20260946', 'date': '2026-09-17', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '葡萄', 'category': '水果', 'unit_price': 12.8}, 'quantity': 101, 'total_amount': 1292.8, 'payment_method': '支付宝'}, {'order_id': 'SO20260947', 'date': '2026-09-18', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '牛奶', 'category': '乳制品', 'unit_price': 12.0}, 'quantity': 159, 'total_amount': 1908.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260948', 'date': '2026-09-19', 'store': '广州天河店', 'region': '华南', 'product': {'name': '蛋糕', 'category': '烘焙', 'unit_price': 28.0}, 'quantity': 34, 'total_amount': 952.0, 'payment_method': '现金'}, {'order_id': 'SO20260949', 'date': '2026-09-20', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '蛋糕', 'category': '烘焙', 'unit_price': 28.0}, 'quantity': 128, 'total_amount': 3584.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260950', 'date': '2026-09-21', 'store': '广州珠江新城店', 'region': '华南', 'product': {'name': '香蕉', 'category': '水果', 'unit_price': 3.2}, 'quantity': 31, 'total_amount': 99.2, 'payment_method': '银行卡'}, {'order_id': 'SO20260951', 'date': '2026-09-22', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '牛奶', 'category': '乳制品', 'unit_price': 12.0}, 'quantity': 182, 'total_amount': 2184.0, 'payment_method': '支付宝'}, {'order_id': 'SO20260952', 'date': '2026-09-23', 'store': '广州天河店', 'region': '华南', 'product': {'name': '鸡胸肉', 'category': '肉禽', 'unit_price': 22.0}, 'quantity': 57, 'total_amount': 1254.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260953', 'date': '2026-09-24', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '橙子', 'category': '水果', 'unit_price': 6.0}, 'quantity': 11, 'total_amount': 66.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260954', 'date': '2026-09-25', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '香蕉', 'category': '水果', 'unit_price': 3.2}, 'quantity': 137, 'total_amount': 438.4, 'payment_method': '银行卡'}, {'order_id': 'SO20260955', 'date': '2026-09-26', 'store': '深圳南山店', 'region': '华南', 'product': {'name': '橙子', 'category': '水果', 'unit_price': 6.0}, 'quantity': 62, 'total_amount': 372.0, 'payment_method': '银行卡'}, {'order_id': 'SO20260956', 'date': '2026-09-27', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '葡萄', 'category': '水果', 'unit_price': 12.8}, 'quantity': 199, 'total_amount': 2547.2, 'payment_method': '支付宝'}, {'order_id': 'SO20260957', 'date': '2026-09-28', 'store': '北京中关村店', 'region': '华北', 'product': {'name': '葡萄', 'category': '水果', 'unit_price': 12.8}, 'quantity': 194, 'total_amount': 2483.2, 'payment_method': '支付宝'}, {'order_id': 'SO20260958', 'date': '2026-09-29', 'store': '上海浦东店', 'region': '华东', 'product': {'name': '葡萄', 'category': '水果', 'unit_price': 12.8}, 'quantity': 131, 'total_amount': 1676.8, 'payment_method': '银行卡'}, {'order_id': 'SO20260959', 'date': '2026-09-30', 'store': '广州天河店', 'region': '华南', 'product': {'name': '苹果', 'category': '水果', 'unit_price': 8.5}, 'quantity': 76, 'total_amount': 646.0, 'payment_method': '现金'}]
<class 'dict'>

                                              product
0   {'name': '酸奶', 'category': '乳制品', 'unit_price'...
1   {'name': '香蕉', 'category': '水果', 'unit_price':...
2   {'name': '三文鱼', 'category': '水产', 'unit_price'...
3   {'name': '苹果', 'category': '水果', 'unit_price':...
4   {'name': '香蕉', 'category': '水果', 'unit_price':...
5   {'name': '苹果', 'category': '水果', 'unit_price':...
6   {'name': '三文鱼', 'category': '水产', 'unit_price'...
7   {'name': '苹果', 'category': '水果', 'unit_price':...
8   {'name': '牛奶', 'category': '乳制品', 'unit_price'...
9   {'name': '三文鱼', 'category': '水产', 'unit_price'...
10  {'name': '香蕉', 'category': '水果', 'unit_price':...
11  {'name': '酸奶', 'category': '乳制品', 'unit_price'...
12  {'name': '三文鱼', 'category': '水产', 'unit_price'...
13  {'name': '蛋糕', 'category': '烘焙', 'unit_price':...
14  {'name': '蛋糕', 'category': '烘焙', 'unit_price':...
15  {'name': '牛奶', 'category': '乳制品', 'unit_price'...
16  {'name': '香蕉', 'category': '水果', 'unit_price':...
17  {'name': '酸奶', 'category': '乳制品', 'unit_price'...
18  {'name': '香蕉', 'category': '水果', 'unit_price':...
19  {'name': '酸奶', 'category': '乳制品', 'unit_price'...
20  {'name': '苹果', 'category': '水果', 'unit_price':...
21  {'name': '酸奶', 'category': '乳制品', 'unit_price'...
22  {'name': '三文鱼', 'category': '水产', 'unit_price'...
23  {'name': '牛奶', 'category': '乳制品', 'unit_price'...
24  {'name': '苹果', 'category': '水果', 'unit_price':...
25  {'name': '牛奶', 'category': '乳制品', 'unit_price'...
26  {'name': '苹果', 'category': '水果', 'unit_price':...
27  {'name': '三文鱼', 'category': '水产', 'unit_price'...
28  {'name': '葡萄', 'category': '水果', 'unit_price':...
29  {'name': '面包', 'category': '烘焙', 'unit_price':...
30  {'name': '橙子', 'category': '水果', 'unit_price':...
31  {'name': '橙子', 'category': '水果', 'unit_price':...
32  {'name': '面包', 'category': '烘焙', 'unit_price':...
33  {'name': '葡萄', 'category': '水果', 'unit_price':...
34  {'name': '橙子', 'category': '水果', 'unit_price':...
35  {'name': '苹果', 'category': '水果', 'unit_price':...
36  {'name': '牛奶', 'category': '乳制品', 'unit_price'...
37  {'name': '面包', 'category': '烘焙', 'unit_price':...
38  {'name': '橙子', 'category': '水果', 'unit_price':...
39  {'name': '蛋糕', 'category': '烘焙', 'unit_price':...
40  {'name': '面包', 'category': '烘焙', 'unit_price':...
41  {'name': '面包', 'category': '烘焙', 'unit_price':...
42  {'name': '葡萄', 'category': '水果', 'unit_price':...
43  {'name': '酸奶', 'category': '乳制品', 'unit_price'...
44  {'name': '苹果', 'category': '水果', 'unit_price':...
45  {'name': '酸奶', 'category': '乳制品', 'unit_price'...
46  {'name': '葡萄', 'category': '水果', 'unit_price':...
47  {'name': '牛奶', 'category': '乳制品', 'unit_price'...
48  {'name': '蛋糕', 'category': '烘焙', 'unit_price':...
49  {'name': '蛋糕', 'category': '烘焙', 'unit_price':...
50  {'name': '香蕉', 'category': '水果', 'unit_price':...
51  {'name': '牛奶', 'category': '乳制品', 'unit_price'...
52  {'name': '鸡胸肉', 'category': '肉禽', 'unit_price'...
53  {'name': '橙子', 'category': '水果', 'unit_price':...
54  {'name': '香蕉', 'category': '水果', 'unit_price':...
55  {'name': '橙子', 'category': '水果', 'unit_price':...
56  {'name': '葡萄', 'category': '水果', 'unit_price':...
57  {'name': '葡萄', 'category': '水果', 'unit_price':...
58  {'name': '葡萄', 'category': '水果', 'unit_price':...
59  {'name': '苹果', 'category': '水果', 'unit_price':...