In [1]:
# 缺失值的处理
#nan:not a number(如无穷大和无穷小无法用数字表示的)
#None:不存在
#pd.NA:不存在，（倾向于没有数值）
import pandas as pd
import numpy as np

s = pd.Series([12,25,np.nan,None,pd.NA])
df = pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]],columns=['第一列','第二列','第三列'])
print(s)

#查看是否是缺失值(Series中的缺失值)
print(s.isna())
print(s.isnull())

#查看是否是缺失值(DataFrame中的缺失值)
print(df.isna())
print(df.isnull())

print(df.isna().sum(axis=1))#查看缺失值个数(按照行看)
print(df.isnull().sum())#查看缺失值个数(按照列看)
print('-'*30)
#剔除缺失值
print(s.dropna())

print('-'*30)
print(df)
print(df.dropna())#在DataFrame中只要一个index行中存在缺失值,直接整条删除

#如果存在有不想删的(dataFrame中)
print(df.dropna(how='all'))#如果每行所有的值均为缺失值,才删去这一行
print(df.dropna(thresh=2))#如果每行至少有n个(这里为2)不是缺失值就保留
print(df.dropna(thresh=3))
print(df.dropna(axis=1))#剔除一整列的记录
print(df.dropna(subset=['第一列']))#如果某列有缺失值，则删除此列的该位置对应行

#填充缺失值
df = pd.read_csv('data/weather_withna.csv')
df.tail()
df.isna().sum(axis=0)
df.head()
print(df.fillna({'temp_max':20,'wind':2.5}).tail())#使用字典来填充
print(df.fillna(df[['temp_max','wind']].mean()).tail())#使用统计值来填充
print(df.ffill().tail())#用前面的相邻值进行添加front
print(df.bfill().tail())#用后面的相邻值进行填充behind

0      12
1      25
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64
第一列    1
第二列    1
第三列    0
dtype: int64
------------------------------
0    12
1    25
dtype: object
------------------------------
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列 第二列  第三列
1  2.0   3    5
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列 第二列  第三列
1  2.0   3    5
   第三列
0    2
1    5
2    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation   temp_max  temp_min      wind weather
1456  2015-12-27            NaN  15.851468       NaN  3.242055     NaN
1457  2015-12-28            NaN  15.851468       NaN  3.242055     NaN
1458  2015-12-29            NaN  15.851468       NaN  3.242055     NaN
1459  2015-12-30            NaN  15.851468       NaN  3.242055     NaN
1460  2015-12-31           20.6  12.200000       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [5]:
import pandas as pd
data = {
    "name":['alice','alice','bob','alice','jack','bob'],
    "age":[26,25,30,25,35,30],
    "city":['NY','NY','LA','NY','SY','LA']
}

df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SY
5    bob   30   LA

In [15]:
df.duplicated()#一整条记录都与前面相同，则标记为重复，返回Ture
df.drop_duplicates(subset=['name'])#根据指定列去重
df.drop_duplicates(subset=['name'],keep='last')#保留最后一次出现的行

    name  age city
3  alice   25   NY
4   jack   35   SY
5    bob   30   LA

In [72]:
#数据类型的转换
df = pd.read_csv('data/sleep.csv')
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

In [48]:
df['age'] = df['age'].astype('int16')
df.dtypes

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, object): ['Female', 'Male']

In [56]:
df['gender'] = df['gender'].astype('category')

In [60]:
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, object): ['Female', 'Male']

In [76]:
df['is_male'] = df['gender'].map({'Female':True,'Male':False})#map用法,做映射用

In [78]:
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: bool

In [150]:
#数据变形
import pandas as pd
data ={
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df = pd.DataFrame(data)
#分列
df[['first','last']]=df['name'].str.split(" ",expand=True)
df = pd.read_csv('data/sleep.csv')
df.head()
df[['blood_pressure_high','blood_pressure_low']] = df['blood_pressure'].str.split("/",expand=True)

df['blood_pressure_high']=df['blood_pressure_high'].astype('int16')
df['blood_pressure_low']=df['blood_pressure_low'].astype('int16')
df.info()
df.blood_pressure_high.mean()
df.blood_pressure_low.mean()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    object
 2   age                      400 non-null    int64
 3   occupation               400 non-null    object
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    object
 9   blood_pressure           400 non-null    object
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    object
 13  blood_pressure_high      400 non-null    int16
 14  blood_pressure_low       400 non-null    int16
dtypes: float64(2), int16(2), int64(6), object(5)
memory usage: 42.3+ KB

73.04

In [116]:
df.T #行列转置
df
'''
ID name  科目 成绩
1 alice Math 90
1 alice English 88
1 alice Science 95
'''

#宽表转换为长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values('name')

   ID   name       科目  分数
0   1  alice     Math  90
2   1  alice  English  88
4   1  alice  Science  95
1   2    bob     Math  85
3   2    bob  English  92
5   2    bob  Science  89

In [152]:
#长表转宽表
pd.pivot(df2,index=['ID','name'],columns='分数',values='科目')

分数          85       88       89    90       92       95
ID name
1  alice   NaN  English      NaN  Math      NaN  Science
2  bob    Math      NaN  Science   NaN  English      NaN

In [161]:
#数据分箱 pd.cut(x,bins,labels)

import pandas as pd

df = pd.read_csv('data/employees.csv')
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [173]:
df1 = df.head(10)[['employee_id','salary']]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [201]:
pd.cut(df1['salary'],bins=2) #bins=n ,及分成n段区间,起始值、结束值是所有数据的最小值和最大值
#4180~14100~24000
pd.cut(df1['salary'],bins=3).value_counts()
pd.cut(df1['salary'],bins=[0,10000,20000,30000]).value_counts()#bins=list,分成n段区间
df1['收入范围']=pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中','高'])
pd.qcut(df1['salary'],3).value_counts()#按人数区分划分，等频率划分

salary
(12000.0, 24000.0]    4
(4199.999, 6000.0]    3
(6000.0, 12000.0]     3
Name: count, dtype: int64

In [249]:
#睡眠数据
import pandas as pd

df = pd.read_csv('data/sleep.csv')
df.head(10)

df1 = df.head(10)[['person_id','sleep_quality']]
df1
df['睡眠质量']=pd.cut(df['sleep_quality'],bins=3,labels=['差','中','优'])
df['睡眠质量'].value_counts()
df.head(10)
df['gender']=df['gender'].astype('category')
df['gender'].value_counts()
#字符串-->类别-->统计
#数值-->分箱-->统计
print(df['gender'].dtype)
print(df['睡眠质量'].dtype)

category
category

In [269]:
# df.rename() df.set_index() df.reset_index()
df = pd.DataFrame(
    {
        'name':['jack','alice','tom','bob'],
        'age':[20,30,40,50],
        'gender':['female','male','female','male']
    }
)
df.set_index('name',inplace=True)#inplace:作用于该数据框（df此DataFrame上）
df.reset_index(inplace=True)
df.rename(columns={"age":"年龄"},index={0:4})#{老：新}

    name  年龄  gender
4   jack  20  female
1  alice  30    male
2    tom  40  female
3    bob  50    male

In [279]:
#直接通过属性进行赋值
df.index=[1,2,3,4]
df.columns=["姓名","年龄","性别"]
df

      姓名  年龄      性别
1   jack  20  female
2  alice  30    male
3    tom  40  female
4    bob  50    male

In [21]:
#时间数据的处理
import pandas as pd
d = pd.Timestamp('2015-05-31 10:22')
d1 = pd.Timestamp('2015-05-31 15:22')
print(d)
print(type(d))
print("年：",d.year)
print("月：",d.month)
print("日：",d.day)
print(d.hour,d.minute,d.second)
print("季度：",d.quarter)
print("是否是月底：",d.is_month_end)
#方法
print("星期几：",d.day_name())
print("转换为天:",d.to_period("D"))
print("转换为天:",d1.to_period("D"))
print("转换为季度：",d1.to_period("Q"))
print("转换为年度：",d1.to_period("Y"))
print("转换为月度：",d1.to_period("M"))
print("转换为周维度：",d1.to_period("W"))

2015-05-31 10:22:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
年： 2015
月： 5
日： 31
10 22 0
季度： 2
是否是月底： True
星期几： Sunday
转换为天: 2015-05-31
转换为天: 2015-05-31
转换为季度： 2015Q2
转换为年度： 2015
转换为月度： 2015-05
转换为周维度： 2015-05-25/2015-05-31

In [48]:
#字符串转换为日期类型
a = pd.to_datetime('20150228 10:22')
print(a)
print(type(a))
print(a.day_name())

#dataFrame 日期转换
df = pd.DataFrame(
    {
        'sales':[100,200,300],
        'date':['20250601','20250602','20250603']
    }
)
df['datetime'] = pd.to_datetime(df['date'])
df
print(df.info())
print(type(df['datetime']))#series类型不能直接使用day_name()方法，day_name()方法是datetime的
df['week']=df['datetime'].dt.day_name()#使用.dt访问器可以使series类型使用day_name()方法
df['datetime'].dt.year

#csv 日期转换
df = pd.read_csv("data/weather.csv",parse_dates=['date'])#parse_dates：parse解析，parse_dates解析分析为datetime类型，将指定列('date')解析为datetime
#df['datetime'] = pd.to_datetime(df['date'])
#df['datetime'].dt.day_name()
df.info()

2015-02-28 10:22:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
Saturday
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      object
 2   datetime  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 204.0+ bytes
None
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.6+ KB

In [58]:
#日期数据作为索引
#df.set_index('date',inplace = True)#设置完一次就生效需要注释掉
print(df.loc["2013-01":"2013-02"])

            precipitation  temp_max  temp_min  wind  weather
date
2013-01-01            0.0       5.0      -2.8   2.7      sun
2013-01-02            0.0       6.1      -1.1   3.2      sun
2013-01-03            4.1       6.7      -1.7   3.0     rain
2013-01-04            2.5      10.0       2.2   2.8     rain
2013-01-05            3.0       6.7       4.4   3.1     rain
2013-01-06            2.0       7.2       2.8   3.0     rain
2013-01-07            2.3      10.0       4.4   7.3     rain
2013-01-08           16.3      11.7       5.6   6.3     rain
2013-01-09           38.4      10.0       1.7   5.1     rain
2013-01-10            0.3       3.3      -0.6   2.1     snow
2013-01-11            0.0       2.8      -2.8   1.9  drizzle
2013-01-12            0.0       2.8      -3.9   2.0      sun
2013-01-13            0.0       2.2      -4.4   1.5      sun
2013-01-14            0.0       3.3      -2.2   1.3      sun
2013-01-15            0.0       6.7      -0.6   2.3      sun
2013-01-16            0.0       6.1      -3.9   1.8  drizzle
2013-01-17            0.0       3.9      -2.8   1.0  drizzle
2013-01-18            0.0       3.3      -1.1   1.3  drizzle
2013-01-19            0.0       1.1      -0.6   1.9  drizzle
2013-01-20            0.0       3.3      -0.6   2.1  drizzle
2013-01-21            0.0       2.2      -1.7   1.1  drizzle
2013-01-22            0.0       3.3      -1.7   0.6  drizzle
2013-01-23            5.1       7.2       2.2   3.1     rain
2013-01-24            5.8       7.2       1.1   2.6     rain
2013-01-25            3.0      10.6       2.8   2.1     rain
2013-01-26            2.3       8.3       3.9   4.5     rain
2013-01-27            1.8       5.6       3.9   4.5     rain
2013-01-28            7.9       6.1       3.3   3.2     rain
2013-01-29            4.3       8.3       5.0   3.9     rain
2013-01-30            3.6       8.9       6.7   3.9     rain
2013-01-31            3.0       9.4       7.2   4.0     rain
2013-02-01            0.3      11.7       5.0   2.9     rain
2013-02-02            0.0       6.1       2.8   2.0  drizzle
2013-02-03            2.3       8.9       2.8   2.9     rain
2013-02-04            0.0      10.6       6.7   2.6     rain
2013-02-05            3.3      10.0       6.7   5.1     rain
2013-02-06            1.0      10.6       6.1   4.5     rain
2013-02-07            1.3       9.4       3.3   4.1     rain
2013-02-08            0.0       7.8       2.2   1.3      sun
2013-02-09            0.3       8.3       4.4   1.3     rain
2013-02-10            0.0       8.9       1.7   2.0  drizzle
2013-02-11            0.3       8.3       4.4   1.4     rain
2013-02-12            1.0      11.1       7.2   5.6     rain
2013-02-13            2.3       9.4       7.2   4.1     rain
2013-02-14            1.0       9.4       5.6   2.2     rain
2013-02-15            0.0      13.3       5.0   2.4  drizzle
2013-02-16            0.0      11.1       3.9   5.6     rain
2013-02-17            0.0       9.4       4.4   3.4     rain
2013-02-18            0.0       7.8       3.9   1.9     rain
2013-02-19            0.0      10.6       1.7   3.4      sun
2013-02-20            1.5       7.8       1.1   2.1     rain
2013-02-21            0.5       6.7       3.9   6.2     rain
2013-02-22            9.4       7.8       3.9   8.1     rain
2013-02-23            0.3      10.0       3.9   4.6     rain
2013-02-24            0.0       8.9       5.0   5.5     rain
2013-02-25            2.3      10.6       3.3   7.1     rain
2013-02-26            0.5       8.9       3.9   3.8     rain
2013-02-27            4.6      10.0       4.4   1.8     rain
2013-02-28            8.1      11.7       6.7   3.8     rain

In [60]:
#时间间隔
d1 = pd.Timestamp('2013-01-15')
d2 = pd.Timestamp('2023-02-23')
d3 = d2 - d1
print(type(d3))
print(d3)

<class 'pandas._libs.tslibs.timedeltas.Timedelta'>
3691 days 00:00:00

In [66]:
df = pd.read_csv("data/weather.csv",parse_dates=['date'])
df.info()
df['delta'] = df['date'] - df['date'][0]
df.set_index('delta',inplace = True)
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.6+ KB

                date  precipitation  temp_max  temp_min  wind  weather
delta
0 days    2012-01-01            0.0      12.8       5.0   4.7  drizzle
1 days    2012-01-02           10.9      10.6       2.8   4.5     rain
2 days    2012-01-03            0.8      11.7       7.2   2.3     rain
3 days    2012-01-04           20.3      12.2       5.6   4.7     rain
4 days    2012-01-05            1.3       8.9       2.8   6.1     rain
...              ...            ...       ...       ...   ...      ...
1456 days 2015-12-27            8.6       4.4       1.7   2.9     rain
1457 days 2015-12-28            1.5       5.0       1.7   1.3     rain
1458 days 2015-12-29            0.0       7.2       0.6   2.6      fog
1459 days 2015-12-30            0.0       5.6      -1.0   3.4      sun
1460 days 2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [68]:
print(df.loc['10days':'20days'])

              date  precipitation  temp_max  temp_min  wind weather
delta
10 days 2012-01-11            0.0       6.1      -1.1   5.1     sun
11 days 2012-01-12            0.0       6.1      -1.7   1.9     sun
12 days 2012-01-13            0.0       5.0      -2.8   1.3     sun
13 days 2012-01-14            4.1       4.4       0.6   5.3    snow
14 days 2012-01-15            5.3       1.1      -3.3   3.2    snow
15 days 2012-01-16            2.5       1.7      -2.8   5.0    snow
16 days 2012-01-17            8.1       3.3       0.0   5.6    snow
17 days 2012-01-18           19.8       0.0      -2.8   5.0    snow
18 days 2012-01-19           15.2      -1.1      -2.8   1.6    snow
19 days 2012-01-20           13.5       7.2      -1.1   2.3    snow
20 days 2012-01-21            3.0       8.3       3.3   8.2    rain

In [80]:
days = pd.date_range("2025-07-03","2026-02-09",freq="W")#开始结束时间，中间空格时间
days = pd.date_range("2025-07-03",periods = 10,freq="YS")#periods是周期，即重复几次
print(days)

DatetimeIndex(['2026-01-01', '2027-01-01', '2028-01-01', '2029-01-01',
               '2030-01-01', '2031-01-01', '2032-01-01', '2033-01-01',
               '2034-01-01', '2035-01-01'],
              dtype='datetime64[ns]', freq='YS-JAN')

In [83]:
df = pd.read_csv('data/weather.csv',parse_dates=['date'])
#重新采样
df.set_index('date',inplace = True)

In [85]:
df[["temp_max","temp_min"]].resample("YE").mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616

In [87]:
df[["temp_max","temp_min"]].resample("YS").mean()

             temp_max  temp_min
date
2012-01-01  15.276776  7.289617
2013-01-01  16.058904  8.153973
2014-01-01  16.995890  8.662466
2015-01-01  17.427945  8.835616

In [126]:
#分组聚合
# df.groupby('分组的字段')['聚合的字段'].聚合函数()
import pandas as pd

df = pd.read_csv("data/employees.csv")
print(type(df))
print(df.dtypes)
print(df['department_id'].isna().sum())
df.dropna(how='any',subset=['department_id'],inplace = True)
df['department_id'] = df['department_id'].astype('int64')

#计算不同部门的平均薪资
df.groupby('department_id').groups#查看分组
df.groupby('department_id').get_group(20)#查看具体的某个分组数据
df2 = df.groupby('department_id')[['salary']].mean()
df2['salary'] = df2['salary'].round(2)
df2 = df2.reset_index()
df2.sort_values('salary',ascending = False)

<class 'pandas.core.frame.DataFrame'>
employee_id         int64
first_name         object
last_name          object
email              object
phone_number       object
job_id             object
salary            float64
commission_pct    float64
manager_id        float64
department_id     float64
dtype: object
1

    department_id    salary
8              90  19333.33
10            110  10150.00
6              70  10000.00
1              20   9500.00
7              80   8955.88
9             100   8600.00
3              40   6500.00
5              60   5760.00
0              10   4400.00
2              30   4150.00
4              50   3475.56

In [138]:
#计算不同部门不同岗位的平均工资
df2 = df.groupby(['department_id','job_id'])['salary'].mean()
df2 = df2.reset_index()
df2['salary'] = df2['salary'].round(1)
df2.sort_values('salary',ascending = False)

    department_id      job_id   salary
13             90     AD_PRES  24000.0
14             90       AD_VP  17000.0
1              20      MK_MAN  13000.0
11             80      SA_MAN  12200.0
18            110      AC_MGR  12000.0
16            100      FI_MGR  12000.0
4              30      PU_MAN  11000.0
10             70      PR_REP  10000.0
12             80      SA_REP   8396.6
17            110  AC_ACCOUNT   8300.0
15            100  FI_ACCOUNT   7920.0
8              50      ST_MAN   7280.0
5              40      HR_REP   6500.0
2              20      MK_REP   6000.0
9              60     IT_PROG   5760.0
0              10     AD_ASST   4400.0
6              50    SH_CLERK   3215.0
7              50    ST_CLERK   2785.0
3              30    PU_CLERK   2780.0

In [143]:
# 企鹅数据分析
#1.导入必要库
import pandas as pd
import numpy as np
#2.导入数据
df = pd.read_csv('data/penguins.csv')
df.head(5)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [146]:
#3.数据清洗
# 缺失值的检查
print(df.isna().sum())
df.dropna(inplace= True)

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [149]:
df.isna().sum()
len(df)

333

In [157]:
#4.数据特征构造
df['sex'] = df['sex'].astype('category')
df['bill_ratio'] = df['bill_length_mm'] / df['bill_depth_mm']

In [156]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767

In [166]:
#5.数据分析
#数据分箱-把体重分为三个等级
labels = ['低','中','高']
df['mass_level'] = pd.cut(df['body_mass_g'],bins = 3,labels = labels)
print(df['mass_level'].value_counts())
#按岛屿、性别分组分析
df.groupby(['sex']).agg(
    {
        'body_mass_g':['mean','count']
    }
)
df.groupby(['sex','island']).agg(
    {
        'body_mass_g':['mean','count']
    }
)

mass_level
低    150
中    128
高     55
Name: count, dtype: int64

C:\Users\yifan\AppData\Local\Temp\ipykernel_19152\2618033384.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex']).agg(
C:\Users\yifan\AppData\Local\Temp\ipykernel_19152\2618033384.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex','island']).agg(

                  body_mass_g
                         mean count
sex    island
Female Biscoe     4319.375000    80
       Dream      3446.311475    61
       Torgersen  3395.833333    24
Male   Biscoe     5104.518072    83
       Dream      3987.096774    62
       Torgersen  4034.782609    23

In [167]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_ratio,mass_level
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909,低
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115,低
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889,低
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554,低
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,1.907767,低

In [172]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/sleep.csv')
df.head(5)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    object
 2   age                      400 non-null    int64
 3   occupation               400 non-null    object
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    object
 9   blood_pressure           400 non-null    object
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 40.8+ KB

,person_id,age,sleep_duration,sleep_quality,physical_activity_level,stress_level,heart_rate,daily_steps
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000
mean,200.500000,39.950000,8.041250,6.125750,64.985000,5.47250,75.990000,11076.510000
std,115.614301,14.038883,2.390787,1.975733,32.297874,2.80873,15.099334,5364.789364
min,1.000000,18.000000,4.100000,1.000000,10.000000,1.00000,50.000000,2067.000000
25%,100.750000,29.000000,5.900000,4.700000,35.000000,3.00000,63.000000,6165.250000
50%,200.500000,40.000000,8.200000,6.100000,65.500000,5.00000,77.000000,11785.500000
75%,300.250000,49.000000,10.125000,7.425000,94.000000,8.00000,90.000000,15878.000000
max,400.000000,90.000000,12.000000,10.000000,120.000000,10.00000,100.000000,19958.000000

In [180]:
#数据清洗
df.isna().sum()
df.drop(columns = 'sleep_disorder',inplace = True)

KeyError: "['sleep_disorder'] not found in axis"

In [181]:
df.head(5)

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945

In [185]:
df.isna().sum()

person_id                  0
gender                     0
age                        0
occupation                 0
sleep_duration             0
sleep_quality              0
physical_activity_level    0
stress_level               0
bmi_category               0
blood_pressure             0
heart_rate                 0
daily_steps                0
dtype: int64

In [204]:
#数据特征的构造
df['gender'] = df['gender'].astype('category')
df['occupation'].value_counts()
df['occupation'] = df['occupation'].astype('category')
df[['high','low']]=df['blood_pressure'].str.split("/",expand=True)#expand是否分成多列
df.head()

#睡眠质量的分箱
labels = ['低','中','高']
df['sleep_quality_level'] = pd.cut(df['sleep_quality'],bins=3,labels=labels)
age_labels = ['青少年','中年','老年']
df['age_level'] = pd.cut(df['age'],bins=3,labels = age_labels)
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,high,low,sleep_quality_level,age_level
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,124,70,中,青少年
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,131,86,中,中年
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,122,70,中,中年
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,124,72,高,青少年
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,133,78,高,老年

In [206]:
# 数据统计、分析
print(df['bmi_category'].value_counts())

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

In [209]:
#根据不同的bmi分组，睡眠质量
df.groupby(['age_level','bmi_category']).agg(
    {
        'sleep_duration':['mean'],
        'sleep_quality':['mean'],
        'stress_level':['mean']
    }
)

C:\Users\yifan\AppData\Local\Temp\ipykernel_19152\3935349397.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['age_level','bmi_category']).agg(

                       sleep_duration sleep_quality stress_level
                                 mean          mean         mean
age_level bmi_category
青少年       Normal             8.100000      6.332000     4.860000
          Obese              8.250000      6.253448     5.534483
          Overweight         8.214286      6.171429     5.317460
          Underweight        7.603279      5.883607     5.426230
中年        Normal             7.422222      6.650000     4.944444
          Obese              7.805556      6.216667     5.888889
          Overweight         8.246154      5.956410     5.974359
          Underweight        8.497500      5.907500     5.750000
老年        Normal             7.420000      4.240000     4.200000
          Obese              7.900000      5.025000     8.000000
          Overweight         8.971429      6.285714     6.714286
          Underweight       10.500000      6.200000     6.000000